
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##

set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN AN40 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN AN41 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN AM38 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN AM39 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN AF38 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN AF39 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN AD38 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN AD39 [get_ports gty_refclk1n_i[1]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_1 -period 6.4 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_1 -period 6.4 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_1 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_1 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_3 -period 6.4 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_3 -period 6.4 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_3 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_3 -include_generated_clocks] -asynchronous
