set_property SRC_FILE_INFO {cfile:C:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.runs/synth_1/.Xil/Vivado-1980-curlywei-PC/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:Vivado-1980-curlywei-PC/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:clk_wiz_0_inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0/gtwizard_ultrascale_0_in_context.xdc rfile:../../../gty_vcu108.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0/gtwizard_ultrascale_0_in_context.xdc id:2 order:EARLY scoped_inst:example_wrapper_inst/gtwizard_ultrascale_0_inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/constrs_1/imports/imports/gtwizard_ultrascale_0_example_top.xdc rfile:../../../gty_vcu108.srcs/constrs_1/imports/imports/gtwizard_ultrascale_0_example_top.xdc id:3} [current_design]
current_instance clk_wiz_0_inst
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
current_instance
current_instance example_wrapper_inst/gtwizard_ultrascale_0_inst
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.560 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports gtrefclk00_in[0]] -edges {1 2 3} -edge_shift {0.000 -3.161 -6.322} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports gtrefclk00_in[0]] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin AF39 [get_ports mgtrefclk0_x0y3_n]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin AF38 [get_ports mgtrefclk0_x0y3_p]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin BC40 [get_ports hb_gtwiz_reset_all_in]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin L19 [get_ports link_down_latched_reset_in]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin BC9 [get_ports hb_gtwiz_reset_clk_freerun_in_p]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin BC8 [get_ports hb_gtwiz_reset_clk_freerun_in_n]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin AT32 [get_ports link_status_out]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin AV34 [get_ports link_down_latched_out]
