# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_xcvr_data.xci
# IP: The module: 'ila_xcvr_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xcvr_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xcvr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_xcvr_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xcvr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_xcvr_data.xci
# IP: The module: 'ila_xcvr_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xcvr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xcvr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/curlywei/Documents/vcu108/gty_vcu108/gty_vcu108/gty_vcu108.srcs/sources_1/ip/ila_xcvr_data/ila_xcvr_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_xcvr_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
