set_property SRC_FILE_INFO {cfile:/home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0.xdc rfile:../../../../ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/attributes.xdc rfile:../../../../ibert_ultrascale_gty_0/synth/attributes.xdc id:2 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y4 [get_cells QUAD[0].u_q/CH[0].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y5 [get_cells QUAD[0].u_q/CH[1].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y6 [get_cells QUAD[0].u_q/CH[2].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y7 [get_cells QUAD[0].u_q/CH[3].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_COMMON_X0Y1 [get_cells QUAD[0].u_q/u_common/u_gtye3_common]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y12 [get_cells QUAD[1].u_q/CH[0].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y13 [get_cells QUAD[1].u_q/CH[1].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y14 [get_cells QUAD[1].u_q/CH[2].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y15 [get_cells QUAD[1].u_q/CH[3].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_COMMON_X0Y3 [get_cells QUAD[1].u_q/u_common/u_gtye3_common]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y24 [get_cells QUAD[0].u_q/CH[0].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y25 [get_cells QUAD[0].u_q/CH[1].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y26 [get_cells QUAD[0].u_q/CH[2].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y27 [get_cells QUAD[0].u_q/CH[3].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y72 [get_cells QUAD[1].u_q/CH[0].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y73 [get_cells QUAD[1].u_q/CH[1].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y74 [get_cells QUAD[1].u_q/CH[2].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y75 [get_cells QUAD[1].u_q/CH[3].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/TXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/RXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gtye3_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[1].u_q/CH[*].u_ch/u_gtye3_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/RXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/RXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gtye3_channel/RXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD2[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD2[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD2[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD2[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD2[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD3[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD3[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD3[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD3[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gtye3_common/QPLLRSVD3[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD2[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD2[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD2[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD2[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD2[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD3[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD3[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD3[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD3[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[1].u_q/u_common/u_gtye3_common/QPLLRSVD3[4]}]
