set_property SRC_FILE_INFO {cfile:/home/dewei/Documents/vcu108/ibert_GTY_qsfp/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0.xdc rfile:../../../project_1.gen/sources_1/ip/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dewei/Documents/vcu108/ibert_GTY_qsfp/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gty_0/synth/attributes.xdc rfile:../../../project_1.gen/sources_1/ip/ibert_ultrascale_gty_0/synth/attributes.xdc id:2 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y12 [get_cells QUAD0.u_q/CH[0].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y13 [get_cells QUAD0.u_q/CH[1].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y14 [get_cells QUAD0.u_q/CH[2].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_CHANNEL_X0Y15 [get_cells QUAD0.u_q/CH[3].u_ch/u_gtye3_channel]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE3_COMMON_X0Y3 [get_cells QUAD0.u_q/u_common/u_gtye3_common]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y72 [get_cells QUAD0.u_q/CH[0].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y73 [get_cells QUAD0.u_q/CH[1].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y74 [get_cells QUAD0.u_q/CH[2].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y75 [get_cells QUAD0.u_q/CH[3].u_ch/u_buf_dmonitorclk]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/TXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/RXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD0.u_q/CH[*].u_ch/u_gtye3_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/RXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/RXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD*.u_q/CH[*].u_ch/u_gtye3_channel/RXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD2[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD2[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD2[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD2[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD2[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD3[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD3[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD3[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD3[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD0.u_q/u_common/u_gtye3_common/QPLLRSVD3[4]}]
