# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/ibert_ultrascale_gty_0.xci
# IP: The module: 'ibert_ultrascale_gty_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/sw_mcs_all.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/attributes.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/ibert_ultrascale_gty_0.xci
# IP: The module: 'ibert_ultrascale_gty_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/ibert_ultrascale_gty_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/sw_mcs_all.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dewei/Documents/VCU108_ibert/ibert_ultrascale_gty_0/synth/attributes.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gty_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
